### ISSUE TITLE
Formula update to squish warning

### ISSUE THREAD

**Issue by caius** [semaphoreci/homebrew-tap#1]
Homebrew has deprecated the `bottle :unneeded` declaration, every time brew is run I'm seeing the following warning appear:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the semaphoreci/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/semaphoreci/homebrew-tap/Formula/sem.rb:9
```

Initially I forked and updated the `sem` Formula to just remove the declaration in https://github.com/caius/semaphoreci-tap/commit/c4d3faa05287347421942a7712f8cd62bd397a70 but then noticed these Formula are output from GoReleaser automagically and you likely have a pipeline to shuffle them through.

It looks like GoReleaser updated their Formula template in https://github.com/goreleaser/goreleaser/pull/2591 to remove this, so using goreleaser v0.183.0 or later will include this change.

Could you trigger a new build with an updated goreleaser to update the Formula please?

**Comment by piyushwadhwa7** [comment]
@semaphoreci

**Comment by AleksandarCole** [comment]
Thank you for reporting this one @caius, the engineering team is working on the new release of `sem` cli that should resolve this.

**Comment by lucaspin** [comment]
This should be fixed now.

**Comment by caius** [comment]
:+1: Confirmed it doesn't output a warning anymore when running `brew`. Thanks!
